- repo: git://github.com/pre-commit/mirrors-yapf
  rev: HEAD
  hooks:
  - id: yapf
- repo: git://github.com/sveitser/pytest-mirror
  rev: HEAD
  hooks:
  - id: pytest
    args: []
- repo: git://github.com/pre-commit/mirrors-pylint
  rev: HEAD
  hooks:
  - id: pylint
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: HEAD
  hooks:
  - id: flake8
- repo: git://github.com/OJFord/pre-commit-mypy
  sha: HEAD
  hooks:
  - id: mypy
